"""empty message

Revision ID: 41427b201911
Revises: c12210f20827
Create Date: 2019-09-25 18:47:17.205870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41427b201911'
down_revision = 'c12210f20827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###
